name: Approval Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: Run a script
      run: |
        echo "I have running a job in dev environment"
        
  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: dev
    steps:
    - uses: actions/checkout@v3
    - name: Run a script
      run: |
        echo "I have running a job in QA environment"
        
  Prod:
    runs-on: ubuntu-latest
    environment: Prod
    needs: QA
    steps:
    - uses: actions/checkout@v3
    - name: Run a script
      run: |
        echo "I have running a job in Prod environment"
